#pragma once
#include "Clever/EventSystem/CleverKeyCodes.h"
#include <GLFW/glfw3.h>
#include <unordered_map>

using namespace InputCodes;

static std::unordered_map<int, int> keyboardGLFWtoCleverKeyCodes
{
	{GLFW_KEY_SPACE  		, Keyboard::KEY_SPACE} 		  			 ,
	{GLFW_KEY_APOSTROPHE	, Keyboard::KEY_APOSTROPHE}	  			 ,
	{GLFW_KEY_COMMA			, Keyboard::KEY_COMMA}		  			 ,
	{GLFW_KEY_MINUS			, Keyboard::KEY_MINUS}		  			 ,
	{GLFW_KEY_PERIOD		, Keyboard::KEY_PERIOD}					 ,
	{GLFW_KEY_SLASH			, Keyboard::KEY_SLASH}					 ,
	{GLFW_KEY_0				, Keyboard::KEY_0}			  			 ,
	{GLFW_KEY_1				, Keyboard::KEY_1}			  			 ,
	{GLFW_KEY_2				, Keyboard::KEY_2}			  			 ,
	{GLFW_KEY_3				, Keyboard::KEY_3}			  			 ,
	{GLFW_KEY_4				, Keyboard::KEY_4}			  			 ,
	{GLFW_KEY_5				, Keyboard::KEY_5}			  			 ,
	{GLFW_KEY_6				, Keyboard::KEY_6}			  			 ,
	{GLFW_KEY_7				, Keyboard::KEY_7}			  			 ,
	{GLFW_KEY_8				, Keyboard::KEY_8}			  			 ,
	{GLFW_KEY_9				, Keyboard::KEY_9}			  			 ,
	{GLFW_KEY_SEMICOLON		, Keyboard::KEY_SEMICOLON}				 ,
	{GLFW_KEY_EQUAL			, Keyboard::KEY_EQUAL}					 ,
	{GLFW_KEY_A				, Keyboard::KEY_A}			  			 ,
	{GLFW_KEY_B				, Keyboard::KEY_B}			  			 ,
	{GLFW_KEY_C				, Keyboard::KEY_C}			  			 ,
	{GLFW_KEY_D				, Keyboard::KEY_D}			  			 ,
	{GLFW_KEY_E				, Keyboard::KEY_E}			  			 ,
	{GLFW_KEY_F				, Keyboard::KEY_F}			  			 ,
	{GLFW_KEY_G				, Keyboard::KEY_G}			  			 ,
	{GLFW_KEY_H				, Keyboard::KEY_H}			  			 ,
	{GLFW_KEY_I				, Keyboard::KEY_I}			  			 ,
	{GLFW_KEY_J				, Keyboard::KEY_J}			  			 ,
	{GLFW_KEY_K				, Keyboard::KEY_K}			  			 ,
	{GLFW_KEY_L				, Keyboard::KEY_L}			  			 ,
	{GLFW_KEY_M				, Keyboard::KEY_M}			  			 ,
	{GLFW_KEY_N				, Keyboard::KEY_N}			  			 ,
	{GLFW_KEY_O				, Keyboard::KEY_O}			  			 ,
	{GLFW_KEY_P				, Keyboard::KEY_P}			  			 ,
	{GLFW_KEY_Q				, Keyboard::KEY_Q}			  			 ,
	{GLFW_KEY_R				, Keyboard::KEY_R}			  			 ,
	{GLFW_KEY_S				, Keyboard::KEY_S}			  			 ,
	{GLFW_KEY_T				, Keyboard::KEY_T}			  			 ,
	{GLFW_KEY_U				, Keyboard::KEY_U}			  			 ,
	{GLFW_KEY_V				, Keyboard::KEY_V}			  			 ,
	{GLFW_KEY_W				, Keyboard::KEY_W}			  			 ,
	{GLFW_KEY_X				, Keyboard::KEY_X}			  			 ,
	{GLFW_KEY_Y				, Keyboard::KEY_Y}			  			 ,
	{GLFW_KEY_Z				, Keyboard::KEY_Z}			  			 ,
	{GLFW_KEY_LEFT_BRACKET	, Keyboard::KEY_LEFT_BRACKET}			 ,
	{GLFW_KEY_BACKSLASH		, Keyboard::KEY_BACKSLASH}				 ,
	{GLFW_KEY_RIGHT_BRACKET	, Keyboard::KEY_RIGHT_BRACKET}			 ,
	{GLFW_KEY_GRAVE_ACCENT	, Keyboard::KEY_GRAVE}					 ,
	{GLFW_KEY_ESCAPE		, Keyboard::KEY_ESCAPE}					 ,
	{GLFW_KEY_ENTER			, Keyboard::KEY_ENTER}					 ,
	{GLFW_KEY_TAB			, Keyboard::KEY_TAB}					 ,
	{GLFW_KEY_BACKSPACE		, Keyboard::KEY_BACKSPACE}				 ,
	{GLFW_KEY_INSERT		, Keyboard::KEY_INSERT}					 ,
	{GLFW_KEY_DELETE		, Keyboard::KEY_DELETE}					 ,
	{GLFW_KEY_RIGHT			, Keyboard::KEY_RIGHT_ARROW}			 ,
	{GLFW_KEY_LEFT			, Keyboard::KEY_LEFT_ARROW}				 ,
	{GLFW_KEY_DOWN			, Keyboard::KEY_DOWN_ARROW}				 ,
	{GLFW_KEY_UP			, Keyboard::KEY_UP_ARROW}				 ,
	{GLFW_KEY_PAGE_UP		, Keyboard::KEY_PAGE_UP}				 ,
	{GLFW_KEY_PAGE_DOWN		, Keyboard::KEY_PAGE_DOWN}				 ,
	{GLFW_KEY_HOME			, Keyboard::KEY_HOME}					 ,
	{GLFW_KEY_END			, Keyboard::KEY_END}					 ,
	{GLFW_KEY_CAPS_LOCK		, Keyboard::KEY_CAPS_LOCK}				 ,
	{GLFW_KEY_SCROLL_LOCK	, Keyboard::KEY_SCROLL_LOCK}			 ,
	{GLFW_KEY_PRINT_SCREEN	, Keyboard::KEY_PRINTSCREEN}			 ,
	{GLFW_KEY_PAUSE			, Keyboard::KEY_PAUSE}					 ,
	{GLFW_KEY_F1			, Keyboard::KEY_F1}			  			 ,
	{GLFW_KEY_F2			, Keyboard::KEY_F2}			  			 ,
	{GLFW_KEY_F3			, Keyboard::KEY_F3}			  			 ,
	{GLFW_KEY_F4			, Keyboard::KEY_F4}			  			 ,
	{GLFW_KEY_F5			, Keyboard::KEY_F5}			  			 ,
	{GLFW_KEY_F6			, Keyboard::KEY_F6}			  			 ,
	{GLFW_KEY_F7			, Keyboard::KEY_F7}			  			 ,
	{GLFW_KEY_F8			, Keyboard::KEY_F8}			  			 ,
	{GLFW_KEY_F9			, Keyboard::KEY_F9}			  			 ,
	{GLFW_KEY_F10			, Keyboard::KEY_F10}					 ,
	{GLFW_KEY_F11			, Keyboard::KEY_F11}					 ,
	{GLFW_KEY_F12			, Keyboard::KEY_F12}					 ,
	{GLFW_KEY_KP_0			, Keyboard::KEY_KEYPAD_0}				 ,
	{GLFW_KEY_KP_1			, Keyboard::KEY_KEYPAD_1}				 ,
	{GLFW_KEY_KP_2			, Keyboard::KEY_KEYPAD_2}				 ,
	{GLFW_KEY_KP_3			, Keyboard::KEY_KEYPAD_3}				 ,
	{GLFW_KEY_KP_4			, Keyboard::KEY_KEYPAD_4}				 ,
	{GLFW_KEY_KP_5			, Keyboard::KEY_KEYPAD_5}				 ,
	{GLFW_KEY_KP_6			, Keyboard::KEY_KEYPAD_6}				 ,
	{GLFW_KEY_KP_7			, Keyboard::KEY_KEYPAD_7}				 ,
	{GLFW_KEY_KP_8			, Keyboard::KEY_KEYPAD_8}				 ,
	{GLFW_KEY_KP_9			, Keyboard::KEY_KEYPAD_9}				 ,
	{GLFW_KEY_KP_DECIMAL	, Keyboard::KEY_KEYPAD_DECIMAL}			 ,
	{GLFW_KEY_KP_DIVIDE		, Keyboard::KEY_KEYPAD_DIVIDE}			 ,
	{GLFW_KEY_KP_MULTIPLY	, Keyboard::KEY_KEYPAD_MULTIPLY}		 ,
	{GLFW_KEY_KP_SUBTRACT	, Keyboard::KEY_KEYPAD_SUBTRACT}		 ,
	{GLFW_KEY_KP_ADD		, Keyboard::KEY_KEYPAD_ADD}				 ,
	{GLFW_KEY_KP_ENTER		, Keyboard::KEY_KEYPAD_ENTER}			 ,
	{GLFW_KEY_LEFT_SHIFT	, Keyboard::KEY_LEFT_SHIFT}				 ,
	{GLFW_KEY_LEFT_CONTROL	, Keyboard::KEY_LEFT_CONTROL}			 ,
	{GLFW_KEY_LEFT_ALT		, Keyboard::KEY_LEFT_ALT}				 ,
	{GLFW_KEY_RIGHT_SHIFT	, Keyboard::KEY_RIGHT_SHIFT}			 ,
	{GLFW_KEY_RIGHT_CONTROL	, Keyboard::KEY_RIGHT_CONTROL}			 ,
	{GLFW_KEY_RIGHT_ALT		, Keyboard::KEY_RIGHT_ALT}

};

static std::unordered_map<int, int> keyboardCleverToGLFWKeyCodes
{
	{Keyboard::KEY_SPACE 		  	,	GLFW_KEY_SPACE  	},
	{Keyboard::KEY_APOSTROPHE	  	,	GLFW_KEY_APOSTROPHE	},
	{Keyboard::KEY_COMMA		  	,	GLFW_KEY_COMMA		},
	{Keyboard::KEY_MINUS		  	,	GLFW_KEY_MINUS		},
	{Keyboard::KEY_PERIOD			,	GLFW_KEY_PERIOD		},
	{Keyboard::KEY_SLASH			,	GLFW_KEY_SLASH		},
	{Keyboard::KEY_0			  	,	GLFW_KEY_0			},
	{Keyboard::KEY_1			  	,	GLFW_KEY_1			},
	{Keyboard::KEY_2			  	,	GLFW_KEY_2			},
	{Keyboard::KEY_3			  	,	GLFW_KEY_3			},
	{Keyboard::KEY_4			  	,	GLFW_KEY_4			},
	{Keyboard::KEY_5			  	,	GLFW_KEY_5			},
	{Keyboard::KEY_6			  	,	GLFW_KEY_6			},
	{Keyboard::KEY_7			  	,	GLFW_KEY_7			},
	{Keyboard::KEY_8			  	,	GLFW_KEY_8			},
	{Keyboard::KEY_9			  	,	GLFW_KEY_9			},
	{Keyboard::KEY_SEMICOLON		,	GLFW_KEY_SEMICOLON	},
	{Keyboard::KEY_EQUAL			,	GLFW_KEY_EQUAL		},
	{Keyboard::KEY_A			  	,	GLFW_KEY_A			},
	{Keyboard::KEY_B			  	,	GLFW_KEY_B			},
	{Keyboard::KEY_C			  	,	GLFW_KEY_C			},
	{Keyboard::KEY_D			  	,	GLFW_KEY_D			},
	{Keyboard::KEY_E			  	,	GLFW_KEY_E			},
	{Keyboard::KEY_F			  	,	GLFW_KEY_F			},
	{Keyboard::KEY_G			  	,	GLFW_KEY_G			},
	{Keyboard::KEY_H			  	,	GLFW_KEY_H			},
	{Keyboard::KEY_I			  	,	GLFW_KEY_I			},
	{Keyboard::KEY_J			  	,	GLFW_KEY_J			},
	{Keyboard::KEY_K			  	,	GLFW_KEY_K			},
	{Keyboard::KEY_L			  	,	GLFW_KEY_L			},
	{Keyboard::KEY_M			  	,	GLFW_KEY_M			},
	{Keyboard::KEY_N			  	,	GLFW_KEY_N			},
	{Keyboard::KEY_O			  	,	GLFW_KEY_O			},
	{Keyboard::KEY_P			  	,	GLFW_KEY_P			},
	{Keyboard::KEY_Q			  	,	GLFW_KEY_Q			},
	{Keyboard::KEY_R			  	,	GLFW_KEY_R			},
	{Keyboard::KEY_S			  	,	GLFW_KEY_S			},
	{Keyboard::KEY_T			  	,	GLFW_KEY_T			},
	{Keyboard::KEY_U			  	,	GLFW_KEY_U			},
	{Keyboard::KEY_V			  	,	GLFW_KEY_V			},
	{Keyboard::KEY_W			  	,	GLFW_KEY_W			},
	{Keyboard::KEY_X			  	,	GLFW_KEY_X			},
	{Keyboard::KEY_Y			  	,	GLFW_KEY_Y			},
	{Keyboard::KEY_Z			  	,	GLFW_KEY_Z			},
	{Keyboard::KEY_LEFT_BRACKET		,   GLFW_KEY_LEFT_BRACKET	},
	{Keyboard::KEY_BACKSLASH		,	GLFW_KEY_BACKSLASH	}	,
	{Keyboard::KEY_RIGHT_BRACKET	,	GLFW_KEY_RIGHT_BRACKET}	,
	{Keyboard::KEY_GRAVE			,	GLFW_KEY_GRAVE_ACCENT	},
	{Keyboard::KEY_ESCAPE			,	GLFW_KEY_ESCAPE		},
	{Keyboard::KEY_ENTER			,	GLFW_KEY_ENTER		}	,
	{Keyboard::KEY_TAB				,	GLFW_KEY_TAB			},
	{Keyboard::KEY_BACKSPACE		,	GLFW_KEY_BACKSPACE	}	,
	{Keyboard::KEY_INSERT			,	GLFW_KEY_INSERT		},
	{Keyboard::KEY_DELETE			,	GLFW_KEY_DELETE		},
	{Keyboard::KEY_RIGHT_ARROW		,	GLFW_KEY_RIGHT		}	,
	{Keyboard::KEY_LEFT_ARROW		,	GLFW_KEY_LEFT			},
	{Keyboard::KEY_DOWN_ARROW		,	GLFW_KEY_DOWN			},
	{Keyboard::KEY_UP_ARROW			,   GLFW_KEY_UP				},
	{Keyboard::KEY_PAGE_UP			,	GLFW_KEY_PAGE_UP		},
	{Keyboard::KEY_PAGE_DOWN		,	GLFW_KEY_PAGE_DOWN	}	,
	{Keyboard::KEY_HOME				,   GLFW_KEY_HOME				},
	{Keyboard::KEY_END				,	GLFW_KEY_END			},
	{Keyboard::KEY_CAPS_LOCK		,	GLFW_KEY_CAPS_LOCK	}	,
	{Keyboard::KEY_SCROLL_LOCK		,	GLFW_KEY_SCROLL_LOCK	},
	{Keyboard::KEY_PRINTSCREEN		,	GLFW_KEY_PRINT_SCREEN	},
	{Keyboard::KEY_PAUSE			,	GLFW_KEY_PAUSE		}	,
	{Keyboard::KEY_F1			  	,	GLFW_KEY_F1			},
	{Keyboard::KEY_F2			  	,	GLFW_KEY_F2			},
	{Keyboard::KEY_F3			  	,	GLFW_KEY_F3			},
	{Keyboard::KEY_F4			  	,	GLFW_KEY_F4			},
	{Keyboard::KEY_F5			  	,	GLFW_KEY_F5			},
	{Keyboard::KEY_F6			  	,	GLFW_KEY_F6			},
	{Keyboard::KEY_F7			  	,	GLFW_KEY_F7			},
	{Keyboard::KEY_F8			  	,	GLFW_KEY_F8			},
	{Keyboard::KEY_F9			  	,	GLFW_KEY_F9			},
	{Keyboard::KEY_F10				,	GLFW_KEY_F10			},
	{Keyboard::KEY_F11				,   GLFW_KEY_F11				},
	{Keyboard::KEY_F12				,   GLFW_KEY_F12				},
	{Keyboard::KEY_KEYPAD_0			,   GLFW_KEY_KP_0				},
	{Keyboard::KEY_KEYPAD_1			,   GLFW_KEY_KP_1				},
	{Keyboard::KEY_KEYPAD_2			,   GLFW_KEY_KP_2				},
	{Keyboard::KEY_KEYPAD_3			,   GLFW_KEY_KP_3				},
	{Keyboard::KEY_KEYPAD_4			,   GLFW_KEY_KP_4				},
	{Keyboard::KEY_KEYPAD_5			,   GLFW_KEY_KP_5				},
	{Keyboard::KEY_KEYPAD_6			,   GLFW_KEY_KP_6				},
	{Keyboard::KEY_KEYPAD_7			,   GLFW_KEY_KP_7				},
	{Keyboard::KEY_KEYPAD_8			,   GLFW_KEY_KP_8				},
	{Keyboard::KEY_KEYPAD_9			,   GLFW_KEY_KP_9				},
	{Keyboard::KEY_KEYPAD_DECIMAL	,	GLFW_KEY_KP_DECIMAL	},
	{Keyboard::KEY_KEYPAD_DIVIDE	,	GLFW_KEY_KP_DIVIDE	}	,
	{Keyboard::KEY_KEYPAD_MULTIPLY	,	GLFW_KEY_KP_MULTIPLY	},
	{Keyboard::KEY_KEYPAD_SUBTRACT	,	GLFW_KEY_KP_SUBTRACT	},
	{Keyboard::KEY_KEYPAD_ADD		,	GLFW_KEY_KP_ADD		},
	{Keyboard::KEY_KEYPAD_ENTER		,   GLFW_KEY_KP_ENTER			},
	{Keyboard::KEY_LEFT_SHIFT		,	GLFW_KEY_LEFT_SHIFT	},
	{Keyboard::KEY_LEFT_CONTROL		,   GLFW_KEY_LEFT_CONTROL		},
	{Keyboard::KEY_LEFT_ALT			,   GLFW_KEY_LEFT_ALT			},
	{Keyboard::KEY_RIGHT_SHIFT		,	GLFW_KEY_RIGHT_SHIFT	},
	{Keyboard::KEY_RIGHT_CONTROL	,	GLFW_KEY_RIGHT_CONTROL}	,
	{Keyboard::KEY_RIGHT_ALT		,	GLFW_KEY_RIGHT_ALT	}
};


static std::unordered_map<int, int> mouseGLFWtoCleverButtonCodes
{
	{GLFW_MOUSE_BUTTON_1, Mouse::BUTTON_1},
	{GLFW_MOUSE_BUTTON_2, Mouse::BUTTON_2},
	{GLFW_MOUSE_BUTTON_3, Mouse::BUTTON_3}
};

static std::unordered_map<int, int> mouseClevertoGLFWButtonCodes
{
	{Mouse::BUTTON_1, GLFW_MOUSE_BUTTON_1},
	{Mouse::BUTTON_2, GLFW_MOUSE_BUTTON_2},
	{Mouse::BUTTON_3, GLFW_MOUSE_BUTTON_3}
};